// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBNCA7rCjVCrur6EtQzZPpfIf5eIbTC6AE',
    appId: '1:395752194022:web:509d9e6559d287318a2027',
    messagingSenderId: '395752194022',
    projectId: 'soptify-3bb4f',
    authDomain: 'soptify-3bb4f.firebaseapp.com',
    storageBucket: 'soptify-3bb4f.firebasestorage.app',
    measurementId: 'G-VBK0TJV2B7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBS6WV1zmNocbpleb04i7cYLGIj-c5VkiQ',
    appId: '1:395752194022:android:caac5ae8c606a9718a2027',
    messagingSenderId: '395752194022',
    projectId: 'soptify-3bb4f',
    storageBucket: 'soptify-3bb4f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBGM8m7nMnbDWAza0kMYTEU_aV4Kw8wq3Q',
    appId: '1:395752194022:ios:ec1b35061a09aa078a2027',
    messagingSenderId: '395752194022',
    projectId: 'soptify-3bb4f',
    storageBucket: 'soptify-3bb4f.firebasestorage.app',
    iosBundleId: 'com.example.soptify',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBGM8m7nMnbDWAza0kMYTEU_aV4Kw8wq3Q',
    appId: '1:395752194022:ios:ec1b35061a09aa078a2027',
    messagingSenderId: '395752194022',
    projectId: 'soptify-3bb4f',
    storageBucket: 'soptify-3bb4f.firebasestorage.app',
    iosBundleId: 'com.example.soptify',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBNCA7rCjVCrur6EtQzZPpfIf5eIbTC6AE',
    appId: '1:395752194022:web:b9bc32646f4293138a2027',
    messagingSenderId: '395752194022',
    projectId: 'soptify-3bb4f',
    authDomain: 'soptify-3bb4f.firebaseapp.com',
    storageBucket: 'soptify-3bb4f.firebasestorage.app',
    measurementId: 'G-DXB3S5MD01',
  );
}
